### ISSUE TITLE
Impossible to add an interpreter (Windows 10)

### ISSUE THREAD

**Issue by pmascalchi** [sinusphi/venvipy#14]
Very nice tool for its utility! 

I just bumped into the issue that adding an interpreter (in Win 10) opens a file explorer that filters everything except some names with "python" in them.
So no option to be able to select the folder itself (or is it the executable that should be selected?).

As you would guess, this is here:
https://github.com/sinusphi/venvipy/blob/0e7640aa07c1a237fc79fb75db790d0b492b78c3/venvipy/wizard.py#L337

**Comment by sinusphi** [comment]
Hello. Sorry for replying so late. 
I'm glad you like *VenviPy*. 

Well, it's not surprising that you have encountered problems running *VenviPy* on Windows. At the moment *VenviPy* only runs on Linux systems. 

I've been working on adapting the code so that *VenviPy* also runs on Windows for some time. In doing so, however, I had to find out that it is not that easy. I don't know how much experience you have with Python and PyQt, but when using Python under Microsoft Windows you have to manage the Windows-specific behavior reliably. And since I have only developed a few projects on Windows so far, I have not yet been able to write a stable release. 

For that I need a little more experience in dealing with multiple Python installations on a Windows machine. This requires a lot of testing because of the numerous scenarios in which way Python can be installed. 
You might want to take a look at [Using Python on Windows](https://docs.python.org/3.9/using/windows.html#using-python-on-windows) from Python Docs. 

However, I would recommend this [Windows port of *VenviPy*](https://github.com/eruber/venvipy). A great fork by [eruber](https://github.com/eruber).
