### ISSUE TITLE
Can't run "venvipy" or "venvipy-wizard" 

### ISSUE THREAD

**Issue by Nistp** [sinusphi/venvipy#15]
Hi, 

I wanted to try out your virtual environment GUI manager and I proceeded to follow the installation instructions; however, when I initialize a virtual environment to run venvipy, I'm getting a core dumped error and thus can't run the program. The error seems to be related to the Qt framework - am I supposed to have it installed beforehand? 

```(PyVenvGUI) nistp@NistpLinux:~/Programs/Python$ venvipy
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

I'm running a 64-bit Ubuntu 22.04 LTS OS. I've installed the prerequisites. I'm running Python 3.10.4. It says to reinstall the application and I have tried it, but that did not fix the issue. 

Any advice on fixing the issue? Thank you!

**Comment by sinusphi** [comment]
Hi, glad to hear you want to try out VenviPy. 

I remember a few years ago I wanted to give Ubuntu a try and installed Xubuntu (I prefer xfce) beside my primary distro. After I set up my developement environment I tried to run VenviPy from within Visual Studio Code because I wanted to work on it. That's where I ran into the same issue. 

Unfortunately I couldn't find a fix for it and I had to switch back to my primary distro. If you find a solution it would be great if you could post it here, much appreciated. 

I'll include a notice about this issue in the [Readme](https://github.com/sinusphi/venvipy#readme).

**Comment by Nistp** [comment]
@sinusphi 

Hi Joey, silly me, the (at least, 'a') solution is right in the error message! It just indicates that the way the application starts up requires having Gnonme and the Qt app can recognize that it's not being used (that the system uses Wayland), but it's ignoring it. 

A simple solution for the user is to do the following:

`export QT_QPA_PLATFORM=wayland`

which would add an environment variable that would let the Qt ignore the requirement for Gnome and run under Wayland. Doing that has got me to get the application running. 

It might be worth investigating whether it's possible to do automatically or asking the user in the beginning and then exporting the variable; that is up to you, however. The fix above is really simple :)
